name: portal
description: "doctor landing page & portal to creating an account &/or logging in"
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^6.1.2
  go_router: ^14.2.0
  http: ^1.2.1
  uuid: ^4.4.0
  intl: any 
  equatable: ^2.0.5
  email_validator: ^3.0.0
  scrollable_positioned_list: ^0.3.8
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true
  generate: true

  
  assets:
    - assets/images/
    - assets/fonts/
    - assets/lang/


  fonts:
    - family: IBM
      fonts:
        - asset: assets/fonts/font.ttf
          style: normal
          weight: 400

